project:
  type: book

book:
  title: "The People Lab Manual"
  author: "The People Lab"
  date: "last-modified"
  chapters:
    - index.qmd
    - 01_welcome.qmd
    - 02_working-at-tpl.qmd
    - 03_meetings.qmd
    - 04_professional-development.qmd
    - 05_research-data.qmd
    - 06_resources-logistics.qmd
    - 07_communications.qmd
    - 08_ops-admin.qmd

format:
  html:
    theme: cosmo
    toc: true
